import { createClient } from 'next-sanity'
import { readFileSync } from 'fs'

const env = Object.fromEntries(
  readFileSync('.env.local', 'utf-8').split('\n')
    .filter(l => l.includes('=') && !l.startsWith('#'))
    .map(l => [l.split('=')[0].trim(), l.split('=').slice(1).join('=').trim()])
)

const client = createClient({
  projectId: env.NEXT_PUBLIC_SANITY_PROJECT_ID,
  dataset: env.NEXT_PUBLIC_SANITY_DATASET || 'production',
  apiVersion: '2024-01-01',
  useCdn: false,
  token: env.SANITY_API_WRITE_TOKEN || env.SANITY_API_READ_TOKEN,
})

// ── IDs existants ──────────────────────────────────────────────────────────
const AUTHORS = {
  arnaud: '7dc9583e-ea73-4f26-ab5b-c0e84e7bba78',
  nathan: 'e115f944-c05e-407a-bb04-a060e95d9a27',
}
const CATEGORIES = {
  marketing: '46eaf127-506e-4e21-9536-ac85911b459d',
  dev: 'e453fee7-4c29-46c4-9a9f-affc7b3d10cd',
}

function ref(id) { return { _type: 'reference', _ref: id } }
function authorRef(id, key) { return { _type: 'reference', _ref: id, _key: key } }
function catRef(id, key) { return { _type: 'reference', _ref: id, _key: key } }

function block(text, style = 'normal', key) {
  return {
    _type: 'block',
    _key: key || Math.random().toString(36).slice(2, 10),
    style,
    markDefs: [],
    children: [{ _type: 'span', _key: Math.random().toString(36).slice(2, 10), marks: [], text }],
  }
}
function h2(text) { return block(text, 'h2') }
function h3(text) { return block(text, 'h3') }
function p(text) { return block(text, 'normal') }
function quote(text) { return block(text, 'blockquote') }
function bullet(text) {
  return { ...block(text, 'normal'), listItem: 'bullet', level: 1 }
}
function numbered(text) {
  return { ...block(text, 'normal'), listItem: 'number', level: 1 }
}

// ── 20 articles ─────────────────────────────────────────────────────────────
const posts = [
  {
    title: "L'IA dans la relation client : opportunité ou menace pour les PME ?",
    slug: "ia-relation-client-pme-2026",
    excerpt: "Chatbots, personnalisation automatisée, prédiction du churn… L'IA redéfinit le service client. Voici comment les PME peuvent en tirer parti sans perdre leur âme.",
    category: CATEGORIES.marketing,
    authors: [AUTHORS.arnaud],
    publishedAt: "2026-04-01T08:00:00Z",
    body: [
      h2("L'IA n'est plus réservée aux grandes entreprises"),
      p("En 2026, les outils d'IA pour la relation client sont devenus accessibles à partir de quelques dizaines d'euros par mois. Les PME n'ont plus d'excuse pour ignorer cette révolution."),
      h3("Ce que l'IA peut faire pour vous"),
      bullet("Répondre aux questions fréquentes 24h/24 via chatbot"),
      bullet("Analyser le sentiment client dans les avis en ligne"),
      bullet("Prédire quels clients risquent de partir (churn)"),
      bullet("Personnaliser les offres selon le comportement d'achat"),
      h3("La limite que l'IA ne franchira pas"),
      p("L'IA excelle dans la répétition et l'analyse. Elle échoue dans la nuance émotionnelle, la gestion de crise et la création de lien authentique. Pour une PME, c'est justement ce lien qui constitue l'avantage concurrentiel."),
      quote("Utilisez l'IA pour libérer du temps humain, pas pour le remplacer. Le contact humain reste votre meilleure arme face aux plateformes."),
      h3("Par où commencer ?"),
      numbered("Identifiez votre volume de tickets support récurrents"),
      numbered("Testez un chatbot sur les 10 questions les plus posées"),
      numbered("Mesurez la satisfaction avant/après sur 30 jours"),
      p("L'objectif n'est pas de supprimer des postes, mais d'orienter vos équipes vers les interactions à haute valeur ajoutée."),
    ],
  },
  {
    title: "SEO en 2026 : comment l'IA de Google réécrit les règles du référencement",
    slug: "seo-ia-google-2026-regles",
    excerpt: "Google AI Overviews, SGE, passage indexing… Le SEO connaît sa plus grande mutation depuis 10 ans. Voici ce que vous devez changer dès maintenant dans votre stratégie.",
    category: CATEGORIES.marketing,
    authors: [AUTHORS.nathan],
    publishedAt: "2026-04-03T08:00:00Z",
    body: [
      h2("La mort du SEO traditionnel (et la naissance du GEO)"),
      p("Le Generative Engine Optimization (GEO) s'impose comme la discipline incontournable de 2026. L'objectif n'est plus seulement d'apparaître dans les résultats, mais d'être cité par les moteurs d'IA."),
      h3("Ce qui change vraiment"),
      bullet("Les réponses directes de Google réduisent le taux de clic de 30 à 60 % sur certaines requêtes"),
      bullet("La position 0 (featured snippet) est désormais capturée par l'IA dans 40 % des cas"),
      bullet("Le contenu expert et sourcé est favorisé face au contenu générique"),
      h3("Les nouvelles règles du jeu"),
      p("E-E-A-T (Expérience, Expertise, Autorité, Fiabilité) n'a jamais été aussi important. Google privilégie les auteurs identifiables, les sources citées et les faits vérifiables."),
      quote("En 2026, votre contenu doit mériter d'être cité par une IA, pas seulement trouvé par un algorithme."),
      h3("Actions concrètes à mettre en place"),
      numbered("Structurez vos articles avec des questions/réponses claires (FAQ Schema)"),
      numbered("Signez vos contenus avec un auteur identifié et une biographie"),
      numbered("Ajoutez des données statistiques sourcées dans chaque article"),
      numbered("Créez des pages thématiques profondes plutôt que beaucoup de petits articles"),
    ],
  },
  {
    title: "LinkedIn en 2026 : les stratégies qui génèrent vraiment des leads",
    slug: "linkedin-strategies-leads-2026",
    excerpt: "L'algorithme LinkedIn a radicalement changé. Le reach organique s'est effondré pour certains formats, et décollé pour d'autres. Voici le guide complet pour s'adapter.",
    category: CATEGORIES.marketing,
    authors: [AUTHORS.arnaud],
    publishedAt: "2026-04-05T09:00:00Z",
    body: [
      h2("L'algorithme LinkedIn n'est plus le même"),
      p("Depuis fin 2025, LinkedIn favorise massivement les contenus qui génèrent de vraies conversations. Les posts sans réactions dans les 30 premières minutes sont pénalisés de façon significative."),
      h3("Les formats qui marchent en 2026"),
      bullet("Les carrousels PDF : toujours efficaces, mais uniquement si le contenu est actionnable"),
      bullet("Les posts texte longs avec structure narrative (hook → développement → CTA)"),
      bullet("Les vidéos courtes filmées en conditions réelles (pas de studio)"),
      bullet("Les sondages stratégiques qui révèlent un problème client"),
      h3("Ce qui ne marche plus"),
      bullet("Les articles LinkedIn natifs (reach en chute libre)"),
      bullet("Le partage de liens externes sans valeur ajoutée"),
      bullet("Les posts génériques type 'conseil du lundi'"),
      h3("La stratégie des 3 types de posts"),
      p("Organisez votre calendrier avec 3 types de contenus : 60 % d'expertise (pensées, analyses), 30 % de preuve sociale (résultats clients, cas d'usage), 10 % de vente directe."),
      quote("Sur LinkedIn, les gens n'achètent pas à une entreprise. Ils achètent à une personne. Publiez en votre nom, pas sous le logo."),
    ],
  },
  {
    title: "Performance web : les Core Web Vitals qui font (vraiment) la différence en 2026",
    slug: "core-web-vitals-performance-2026",
    excerpt: "INP remplace FID, LCP reste roi, CLS fait des ravages sur mobile. Décryptage des métriques Google qui impactent votre référencement et vos conversions.",
    category: CATEGORIES.dev,
    authors: [AUTHORS.nathan],
    publishedAt: "2026-04-07T08:00:00Z",
    body: [
      h2("Pourquoi la performance web est devenue un enjeu business"),
      p("Une étude Google montre qu'une amélioration de 100ms du temps de chargement augmente les conversions de 1 %. Sur un site e-commerce à 1M€ de CA, c'est 10 000€ récupérés sans changer une ligne de contenu."),
      h3("Les 3 métriques qui comptent"),
      bullet("LCP (Largest Contentful Paint) : le temps avant que le contenu principal soit visible. Cible : < 2,5s"),
      bullet("INP (Interaction to Next Paint) : remplace FID, mesure la réactivité aux interactions. Cible : < 200ms"),
      bullet("CLS (Cumulative Layout Shift) : les décalages visuels pendant le chargement. Cible : < 0,1"),
      h3("Les coupables les plus fréquents"),
      numbered("Les images non optimisées (pas de width/height, pas de lazy loading)"),
      numbered("Les polices de caractères chargées sans font-display: swap"),
      numbered("Le JavaScript bloquant chargé dans le head"),
      numbered("Les publicités et iframes qui décalent le contenu"),
      h3("Le fix le plus rapide : l'image hero"),
      p("80 % des mauvais scores LCP viennent de l'image principale de la page d'accueil. Utilisez next/image avec priority={true}, définissez des dimensions explicites et servez en format WebP ou AVIF."),
      quote("Vous n'avez pas besoin d'un score parfait. Passer de 40 à 70 sur PageSpeed suffit souvent à récupérer 15 % de trafic organique perdu."),
    ],
  },
  {
    title: "Email marketing en 2026 : les 7 erreurs qui tuent votre délivrabilité",
    slug: "email-marketing-delivrabilite-2026",
    excerpt: "Gmail et Outlook ont durci leurs filtres. Les nouvelles règles DMARC/DKIM sont désormais obligatoires. Voici comment éviter de finir dans les spams.",
    category: CATEGORIES.marketing,
    authors: [AUTHORS.arnaud],
    publishedAt: "2026-04-09T08:00:00Z",
    body: [
      h2("Le contexte : pourquoi la délivrabilité est en crise"),
      p("En 2024, Google et Yahoo ont imposé des exigences strictes d'authentification pour les expéditeurs envoyant plus de 5 000 emails/jour. En 2026, ces règles s'appliquent à partir de 100 envois."),
      h3("Erreur n°1 : ne pas avoir configuré SPF, DKIM et DMARC"),
      p("Ces protocoles prouvent aux fournisseurs de messagerie que vous êtes bien l'expéditeur légitime. Sans eux, vos emails ont 60 % de chances de finir en spam ou d'être rejetés."),
      h3("Erreur n°2 : envoyer à une liste non engagée"),
      p("Si vos abonnés n'ouvrent pas vos emails depuis 6 mois, chaque envoi détériore votre réputation d'expéditeur. Nettoyez régulièrement votre liste."),
      h3("Erreur n°3 : des lignes d'objet trop commerciales"),
      bullet("❌ '50% de réduction - Offre limitée !!!'"),
      bullet("✅ 'La méthode qu'on utilise pour nos clients depuis 6 mois'"),
      h3("Les 4 autres erreurs à éviter"),
      numbered("Envoyer sans désabonnement en un clic (obligatoire depuis 2024)"),
      numbered("Utiliser une adresse no-reply (pénalise l'engagement)"),
      numbered("Intégrer trop d'images par rapport au texte (ratio idéal : 60/40)"),
      numbered("Ignorer le taux de plainte spam (doit rester sous 0,08 %)"),
      quote("Un email qui arrive en boîte inbox avec 20 % d'ouverture vaut infiniment plus que 100 emails qui finissent en spam."),
    ],
  },
  {
    title: "Next.js 15 en production : ce qu'on a appris après 6 mois d'utilisation",
    slug: "nextjs-15-retour-experience-production",
    excerpt: "React Server Components, Turbopack stable, amélioration du cache… Retour d'expérience honnête sur ce que change réellement Next.js 15 pour les projets clients.",
    category: CATEGORIES.dev,
    authors: [AUTHORS.nathan, AUTHORS.arnaud],
    publishedAt: "2026-04-11T09:00:00Z",
    body: [
      h2("Pourquoi on a migré nos projets vers Next.js 15"),
      p("Après avoir testé Next.js 15 en beta pendant 3 mois, on a décidé de l'adopter pour tous nos nouveaux projets. Voici ce qui nous a convaincus, et ce qui nous a surpris."),
      h3("Le vrai gain : la gestion du cache"),
      p("Next.js 14 avait un modèle de cache agressif qui causait des bugs en production difficiles à déboguer. Next.js 15 adopte un opt-in caching : rien n'est mis en cache par défaut, vous choisissez explicitement ce qui l'est."),
      quote("On a perdu 2 jours sur un bug de cache Next.js 14 chez un client. Avec Next.js 15, ce type de problème appartient au passé."),
      h3("Turbopack : enfin vraiment utilisable"),
      bullet("Build de développement 4x plus rapide sur nos projets de taille moyenne"),
      bullet("Hot reload quasi instantané même sur les pages complexes"),
      bullet("Toujours quelques incompatibilités avec certains plugins Webpack"),
      h3("Les React Server Components en pratique"),
      p("Le modèle mental est différent et demande 2 à 3 semaines d'adaptation pour une équipe. Mais les bénéfices sont réels : moins de JavaScript côté client, meilleur SEO, données fetchées au plus près du serveur."),
      h3("Notre verdict"),
      p("Next.js 15 est production-ready. On recommande la migration pour tout nouveau projet. Pour les projets existants en Next.js 14, migrez lors de votre prochain sprint dédié à la performance."),
    ],
  },
  {
    title: "Personal branding pour dirigeants : transformer votre expertise en machine à leads",
    slug: "personal-branding-dirigeants-leads",
    excerpt: "En B2B, les acheteurs font confiance aux personnes avant de faire confiance aux entreprises. Voici comment construire votre marque personnelle de dirigeant en 90 jours.",
    category: CATEGORIES.marketing,
    authors: [AUTHORS.arnaud],
    publishedAt: "2026-04-13T08:00:00Z",
    body: [
      h2("Pourquoi le personal branding est devenu incontournable en B2B"),
      p("Une étude Edelman montre que 63 % des acheteurs B2B se renseignent sur le dirigeant de l'entreprise avant de prendre contact. Votre présence en ligne n'est plus optionnelle."),
      h3("Les 3 piliers d'un personal branding efficace"),
      bullet("Le positionnement : sur quel sujet voulez-vous être reconnu comme expert ?"),
      bullet("La consistance : publiez au minimum 2 fois par semaine pendant 90 jours"),
      bullet("L'authenticité : partagez vos échecs autant que vos succès"),
      h3("Le plan 90 jours"),
      numbered("Semaines 1-2 : définissez votre territoire d'expertise et vos 3 sujets de prédilection"),
      numbered("Semaines 3-6 : publiez du contenu éducatif, ne parlez pas de vente"),
      numbered("Semaines 7-10 : intégrez des preuves sociales (résultats, témoignages)"),
      numbered("Semaines 11-13 : ajoutez des appels à l'action mesurés"),
      quote("Le personal branding ne se construit pas en cherchant à paraître. Il se construit en partageant ce qu'on sait vraiment faire."),
      h3("Mesurer le retour"),
      p("Les indicateurs à suivre : demandes de connexion entrantes, messages directs spontanés, mentions dans des conversations tierces. Le ROI n'est pas immédiat, mais il est durable."),
    ],
  },
  {
    title: "TypeScript strict mode : pourquoi vous ne pouvez plus l'ignorer",
    slug: "typescript-strict-mode-guide-2026",
    excerpt: "Le mode strict de TypeScript effraye les débutants. Pourtant, c'est le meilleur investissement qualité que vous puissiez faire sur un projet. Explications et guide de migration.",
    category: CATEGORIES.dev,
    authors: [AUTHORS.nathan],
    publishedAt: "2026-04-15T08:00:00Z",
    body: [
      h2("Qu'est-ce que le strict mode TypeScript ?"),
      p("Le strict mode active un ensemble de vérifications supplémentaires : strictNullChecks, noImplicitAny, strictFunctionTypes, etc. En clair, TypeScript devient vraiment typé au lieu de faire semblant."),
      h3("Pourquoi la plupart des projets ne l'ont pas activé"),
      p("Par paresse initiale. On démarre un projet avec strict: false pour aller vite, et on ne revient jamais dessus. Résultat : des bugs en production qui auraient été détectés à la compilation."),
      h3("Les bugs que le strict mode aurait évités"),
      bullet("Cannot read property 'x' of undefined — le null check manquant"),
      bullet("Fonction qui retourne string | undefined mais traité comme string"),
      bullet("Paramètre implicitement any qui accepte n'importe quoi"),
      h3("Comment migrer progressivement"),
      numbered("Activez strict: true dans tsconfig.json"),
      numbered("Lancez tsc --noEmit et notez le nombre d'erreurs"),
      numbered("Traitez d'abord les fichiers partagés (utils, types, hooks)"),
      numbered("Utilisez // @ts-expect-error temporairement pour débloquer sans casser"),
      quote("On a migré un projet de 40 000 lignes en 3 sprints. On a trouvé 12 bugs réels que les tests n'avaient pas détectés. Ça valait largement l'effort."),
    ],
  },
  {
    title: "Automatisation marketing : les outils qui font vraiment gagner du temps en 2026",
    slug: "automatisation-marketing-outils-2026",
    excerpt: "Make, n8n, Zapier, HubSpot… Le marché des outils d'automatisation explose. On démêle le vrai du faux et on vous donne notre stack recommandée pour les PME.",
    category: CATEGORIES.marketing,
    authors: [AUTHORS.arnaud],
    publishedAt: "2026-04-17T08:00:00Z",
    body: [
      h2("L'automatisation marketing n'est pas de la magie"),
      p("Beaucoup d'entreprises achètent des outils coûteux sans avoir défini leurs processus. L'automatisation d'un mauvais processus vous donnera seulement de mauvais résultats plus vite."),
      h3("La règle d'or avant d'automatiser"),
      p("Un processus doit avoir été exécuté manuellement avec succès au moins 10 fois avant d'être automatisé. Si vous ne savez pas pourquoi ça marche, vous ne pourrez pas le maintenir."),
      h3("Notre stack recommandée pour PME"),
      bullet("Make (ex-Integromat) : le meilleur rapport puissance/prix pour les flux complexes"),
      bullet("Brevo (ex-Sendinblue) : emailing automation + CRM intégré, interface française"),
      bullet("Cal.com : prise de rendez-vous automatisée, open source"),
      bullet("Notion + Make : base de données interne + automatisations personnalisées"),
      h3("Les 3 automatisations à mettre en place en priorité"),
      numbered("Séquence de bienvenue email : 3 emails sur 7 jours après inscription newsletter"),
      numbered("Relance devis : rappel automatique si pas de réponse après 3 jours"),
      numbered("Rapport hebdomadaire : synthèse des KPIs envoyée chaque lundi matin"),
      quote("Commencez par automatiser une seule chose. Faites-la parfaitement. Puis passez à la suivante."),
    ],
  },
  {
    title: "Publicité Meta vs Google Ads en 2026 : où mettre votre budget ?",
    slug: "meta-vs-google-ads-budget-2026",
    excerpt: "Les CPM augmentent, les cookies disparaissent, les audiences deviennent floues. Comment choisir entre Meta Ads et Google Ads selon votre secteur et vos objectifs.",
    category: CATEGORIES.marketing,
    authors: [AUTHORS.nathan],
    publishedAt: "2026-04-19T09:00:00Z",
    body: [
      h2("Le paysage publicitaire a changé"),
      p("La disparition progressive des cookies tiers et le renforcement du RGPD ont transformé le ciblage publicitaire. Les plateformes ont adapté leurs algorithmes pour fonctionner avec moins de données individuelles."),
      h3("Quand choisir Google Ads"),
      bullet("Votre produit/service répond à un besoin conscient (plombier, avocat, logiciel spécifique)"),
      bullet("Vous visez des conversions immédiates"),
      bullet("Votre cycle de vente est court (< 30 jours)"),
      h3("Quand choisir Meta Ads"),
      bullet("Vous créez un besoin ou éduquez le marché (nouveau produit, secteur peu connu)"),
      bullet("Votre cible est définie par des intérêts ou un style de vie"),
      bullet("Vous avez un budget retargeting conséquent"),
      h3("La vraie question : votre LTV justifie-t-elle le CAC ?"),
      p("Avant de choisir une plateforme, calculez votre coût d'acquisition client acceptable (CAC max = LTV × marge brute). Si votre LTV est inférieure à 500€, les deux plateformes seront difficiles à rentabiliser sans volume."),
      quote("Le meilleur canal publicitaire est celui que vous maîtrisez suffisamment pour l'optimiser. Mieux vaut exceller sur une plateforme qu'être médiocre sur deux."),
      h3("Notre recommandation pour les PME"),
      p("Démarrez avec Google Search (intention = acheteurs chauds), mesurez le CAC sur 60 jours, puis ajoutez Meta Ads en retargeting pour les visiteurs non convertis."),
    ],
  },
  {
    title: "Progressive Web Apps en 2026 : guide de décision pour votre projet",
    slug: "progressive-web-apps-guide-decision-2026",
    excerpt: "PWA vs application native : quand faut-il choisir l'une plutôt que l'autre ? Analyse des cas d'usage, des limitations iOS et des opportunités pour les entreprises.",
    category: CATEGORIES.dev,
    authors: [AUTHORS.nathan],
    publishedAt: "2026-04-21T08:00:00Z",
    body: [
      h2("Les PWA en 2026 : maturité et limites"),
      p("Les Progressive Web Apps ont atteint une maturité suffisante pour couvrir 80 % des cas d'usage mobile d'entreprise. Apple a progressivement ouvert ses APIs sur iOS, même si des restrictions subsistent."),
      h3("Ce que les PWA permettent aujourd'hui"),
      bullet("Notifications push (enfin disponibles sur iOS depuis 2023)"),
      bullet("Accès au système de fichiers (via File System Access API)"),
      bullet("Fonctionnement hors ligne complet avec Service Workers"),
      bullet("Installation sur l'écran d'accueil sans passer par l'App Store"),
      h3("Ce qui reste limité sur iOS"),
      bullet("Accès Bluetooth et NFC : toujours restreint"),
      bullet("Pas de background sync fiable"),
      bullet("Les PWA s'effacent si inutilisées pendant 7 jours (paramètre par défaut)"),
      h3("Qui devrait choisir une PWA ?"),
      p("Les PME qui ont besoin d'une application pour leurs équipes internes ou leurs clients réguliers, sans vouloir gérer deux codebases (iOS + Android). Le coût de développement est divisé par 2 à 3."),
      quote("Si votre application ne nécessite pas d'accès hardware avancé (caméra pro, Bluetooth, capteurs), une PWA bien développée offrira 95 % de l'expérience native pour 40 % du budget."),
    ],
  },
  {
    title: "Analytics post-cookies : comment mesurer sans Google Analytics universel",
    slug: "analytics-post-cookies-alternatives-2026",
    excerpt: "Google Analytics 4 a ses limites, le consentement réduit les données, les bloqueurs de pub explosent. Voici les alternatives et stratégies pour retrouver une mesure fiable.",
    category: CATEGORIES.marketing,
    authors: [AUTHORS.arnaud],
    publishedAt: "2026-04-23T08:00:00Z",
    body: [
      h2("Le problème : vos données analytics sont probablement fausses"),
      p("Entre les bloqueurs de publicité (35 % des internautes français), le refus de consentement (60 % en moyenne) et les limites de Safari ITP, vous perdez potentiellement 50 % de vos données réelles."),
      h3("Les alternatives à Google Analytics 4"),
      bullet("Plausible Analytics : léger, RGPD natif, sans cookies, données 100 % européennes"),
      bullet("Umami : open source, auto-hébergeable, coût zéro"),
      bullet("PostHog : pour aller plus loin (replays de session, heatmaps, feature flags)"),
      h3("La stratégie hybride recommandée"),
      p("Gardez GA4 pour la compatibilité avec Google Ads et Search Console, mais ajoutez un outil sans cookies en parallèle pour avoir vos vrais chiffres. Comparez les deux pour calibrer vos estimations."),
      h3("Le server-side tracking : la vraie solution"),
      p("Le tracking côté serveur contourne les bloqueurs et les restrictions navigateur. Les données passent par votre serveur avant d'être envoyées aux plateformes. Résultat : 20 à 40 % de données récupérées."),
      quote("En 2026, une entreprise qui pilote son activité avec des données analytics tronquées de 50 % prend des décisions sur des fondations sablonneuses."),
    ],
  },
  {
    title: "Accessibilité web RGAA : de l'obligation légale à l'avantage concurrentiel",
    slug: "accessibilite-web-rgaa-avantage-concurrentiel",
    excerpt: "Le RGAA s'impose progressivement au secteur privé français. Au-delà de la conformité, l'accessibilité améliore le SEO, réduit le taux de rebond et élargit votre audience.",
    category: CATEGORIES.dev,
    authors: [AUTHORS.arnaud, AUTHORS.nathan],
    publishedAt: "2026-04-25T08:00:00Z",
    body: [
      h2("Le RGAA n'est plus optionnel"),
      p("Depuis 2024, le Référentiel Général d'Amélioration de l'Accessibilité (RGAA) s'applique aux entreprises de plus de 250 salariés ou 50M€ de CA. D'ici 2027, le seuil descendra à 50 salariés."),
      h3("Les 5 erreurs d'accessibilité les plus fréquentes"),
      numbered("Contraste de texte insuffisant (ratio minimum : 4,5:1 pour le texte normal)"),
      numbered("Images sans attribut alt ou avec un alt non descriptif"),
      numbered("Formulaires sans labels associés aux champs"),
      numbered("Navigation au clavier impossible ou incohérente"),
      numbered("Vidéos sans sous-titres ni transcription"),
      h3("L'avantage SEO souvent oublié"),
      p("Les critères d'accessibilité et de SEO se recoupent à 60 %. Un site accessible a des balises sémantiques correctes, des textes alternatifs pertinents et une structure de navigation claire — exactement ce que Google valorise."),
      quote("Nous avons amélioré le score d'accessibilité d'un client de 35 à 82/100. Le trafic organique a augmenté de 23 % dans les 3 mois suivants, sans toucher au contenu."),
      h3("Par où commencer : l'audit rapide"),
      p("Utilisez axe DevTools (extension Chrome gratuite) pour identifier les erreurs automatiquement détectables. Elles représentent 30 à 40 % des non-conformités RGAA. C'est votre point de départ."),
    ],
  },
  {
    title: "Docker pour les développeurs front : simplifier votre environnement de travail",
    slug: "docker-developpeurs-front-workflow",
    excerpt: "On entend souvent 'Docker c'est pour le back'. Pourtant, conteneuriser son environnement de développement front résout des problèmes concrets de compatibilité et d'onboarding.",
    category: CATEGORIES.dev,
    authors: [AUTHORS.nathan],
    publishedAt: "2026-04-27T09:00:00Z",
    body: [
      h2("Le problème que Docker résout pour le front"),
      p("'Ça marche chez moi' est la phrase la plus coûteuse du développement web. Différentes versions de Node.js, de npm, de dépendances système — Docker élimine ces variables."),
      h3("Le Dockerfile minimal pour un projet Next.js"),
      p("Un Dockerfile de développement se résume à 3 étapes : choisir une image Node officielle, copier les fichiers de configuration, installer les dépendances. L'environnement devient reproductible en une commande."),
      h3("Les 3 bénéfices concrets"),
      bullet("Onboarding réduit de 2 jours à 30 minutes pour un nouveau développeur"),
      bullet("Même comportement sur Mac, Windows et Linux"),
      bullet("Isolation des projets : plus de conflits de versions entre clients"),
      h3("Docker Compose pour les projets avec backend"),
      p("Quand votre front parle à une API et une base de données, Docker Compose orchestre tout l'environnement en un seul fichier. Lancez la totalité du stack avec docker compose up."),
      quote("Le vrai luxe en développement, c'est d'avoir un environnement identique entre votre machine, celle de vos collègues et la CI. Docker est le seul outil qui garantit ça vraiment."),
      h3("Les limites à connaître"),
      bullet("Performance des volumes sur Mac/Windows : plus lent que le natif (20-40 %)"),
      bullet("Hot reload peut nécessiter une configuration spécifique"),
      bullet("Courbe d'apprentissage initiale de 2 à 4 heures"),
    ],
  },
  {
    title: "Tunnel de vente B2B : structurer le parcours client pour raccourcir le cycle",
    slug: "tunnel-vente-b2b-parcours-client-2026",
    excerpt: "En B2B, 90 % des visiteurs de votre site ne sont pas prêts à acheter. Un tunnel bien structuré nourrit la relation jusqu'à la décision. Voici comment le construire.",
    category: CATEGORIES.marketing,
    authors: [AUTHORS.arnaud],
    publishedAt: "2026-04-29T08:00:00Z",
    body: [
      h2("Le mythe du visiteur prêt à acheter"),
      p("Moins de 5 % de vos visiteurs sont en phase de décision active. Les 95 % restants sont en découverte, en évaluation ou en latence. Votre site doit parler à ces 95 % d'abord."),
      h3("Les 3 niveaux du tunnel B2B"),
      numbered("TOFU (Top of Funnel) : éduquer — articles de blog, guides gratuits, comparatifs"),
      numbered("MOFU (Middle of Funnel) : qualifier — webinaires, études de cas, outils diagnostics"),
      numbered("BOFU (Bottom of Funnel) : convertir — audits gratuits, devis, démos personnalisées"),
      h3("L'aimant à prospects par niveau"),
      p("Au TOFU, offrez de la connaissance (guide PDF, checklist). Au MOFU, offrez de l'analyse (audit, benchmark sectoriel). Au BOFU, offrez du temps (30 min de consultation gratuite)."),
      quote("Le CTA 'Contactez-nous' ne convertit que les prospects déjà convaincus. Pour les autres, vous avez besoin d'une étape intermédiaire."),
      h3("Les outils pour automatiser"),
      bullet("Email séquences déclenchées par le téléchargement d'un lead magnet"),
      bullet("Lead scoring basé sur les pages visitées et les emails ouverts"),
      bullet("Retargeting LinkedIn pour les visiteurs de la page pricing"),
      p("Un tunnel B2B bien conçu réduit le cycle de vente de 30 à 50 % en qualifiant les prospects avant le premier appel commercial."),
    ],
  },
  {
    title: "Sécurité web en 2026 : les vulnérabilités à surveiller absolument",
    slug: "securite-web-vulnerabilites-2026",
    excerpt: "Injection via LLM, supply chain attacks, social engineering augmenté par l'IA… Le paysage des menaces a évolué. Voici ce que tout développeur web doit savoir aujourd'hui.",
    category: CATEGORIES.dev,
    authors: [AUTHORS.nathan],
    publishedAt: "2026-05-01T08:00:00Z",
    body: [
      h2("Les nouvelles menaces de 2026"),
      p("Le OWASP Top 10 n'a pas fondamentalement changé, mais de nouveaux vecteurs d'attaque sont apparus avec la généralisation de l'IA. La surface d'attaque s'est élargie."),
      h3("La menace émergente : les attaques sur les LLM intégrés"),
      p("Si votre application expose un chatbot IA, vous avez une nouvelle surface d'attaque : le prompt injection. Un utilisateur malveillant peut manipuler les instructions du modèle pour exfiltrer des données ou contourner des restrictions."),
      h3("Les classiques qui restent critiques"),
      bullet("XSS (Cross-Site Scripting) : toujours dans le top 3, souvent via des librairies tierces"),
      bullet("SQL/NoSQL Injection : en hausse avec les requêtes générées par IA"),
      bullet("IDOR (Insecure Direct Object Reference) : problème de contrôle d'accès souvent oublié"),
      bullet("Dépendances vulnérables : auditez npm audit / pnpm audit à chaque release"),
      h3("Les 5 pratiques minimales"),
      numbered("Activez les Content Security Policy headers sur tous vos projets"),
      numbered("Utilisez des requêtes paramétrées, jamais de concaténation de chaînes SQL"),
      numbered("Validez les données côté serveur, jamais uniquement côté client"),
      numbered("Mettez à jour vos dépendances chaque semaine avec Dependabot ou Renovate"),
      numbered("Activez l'authentification à deux facteurs sur tous vos accès cloud"),
      quote("La sécurité n'est pas un projet, c'est une pratique. Elle doit être intégrée dans chaque pull request, pas auditée une fois par an."),
    ],
  },
  {
    title: "TikTok Business pour les entreprises françaises : ce qui marche vraiment",
    slug: "tiktok-business-entreprises-france-2026",
    excerpt: "TikTok Shop, TikTok Ads, contenu organique B2B… La plateforme a mûri. Mais toutes les entreprises n'ont pas les mêmes chances d'y réussir. Décryptage.",
    category: CATEGORIES.marketing,
    authors: [AUTHORS.arnaud],
    publishedAt: "2026-05-03T09:00:00Z",
    body: [
      h2("TikTok en France en 2026 : les chiffres"),
      p("TikTok compte 22 millions d'utilisateurs actifs en France, avec une médiane d'âge qui remonte à 28 ans. La plateforme n'est plus seulement pour la Gen Z."),
      h3("Les secteurs qui cartonnent"),
      bullet("E-commerce produit (beauté, décoration, alimentation) : TikTok Shop génère des résultats mesurables"),
      bullet("Formation et expertise (le 'edutainment' BtoC et BtoB)"),
      bullet("Artisanat et fabrication : le 'making of' fascine universellement"),
      h3("Ce qui ne marche pas"),
      bullet("La publicité corporate traditionnelle : rejetée massivement"),
      bullet("Le contenu trop produit : la spontanéité surpasse la perfection"),
      bullet("La communication sans régularité : TikTok punit les comptes inactifs"),
      h3("La question pour les PME B2B"),
      p("Si votre cible est des DAF ou des directeurs généraux de 50 ans, TikTok n'est probablement pas votre priorité. Si votre cible est des responsables marketing, des entrepreneurs ou des équipes terrain — la plateforme mérite d'être testée."),
      quote("Avant de créer un compte TikTok, vérifiez si vos clients passent du temps sur la plateforme. Ouvrez l'application et cherchez votre secteur d'activité. Si vous trouvez du contenu concurrent, c'est bon signe."),
    ],
  },
  {
    title: "Headless CMS vs CMS traditionnel : quel choix pour votre prochain site ?",
    slug: "headless-cms-vs-traditionnel-guide-choix",
    excerpt: "WordPress reste dominant mais les alternatives headless (Sanity, Contentful, Strapi) gagnent du terrain. Comment décider en fonction de votre équipe et de vos ambitions ?",
    category: CATEGORIES.dev,
    authors: [AUTHORS.nathan],
    publishedAt: "2026-05-05T08:00:00Z",
    body: [
      h2("La montée en puissance du headless"),
      p("L'approche headless sépare le back-end (gestion de contenu) du front-end (présentation). Résultat : une liberté totale sur le rendu, mais une complexité accrue."),
      h3("Quand choisir un CMS headless"),
      bullet("Votre site doit alimenter plusieurs surfaces : web, app mobile, borne physique"),
      bullet("Vous voulez des performances Core Web Vitals optimales"),
      bullet("Votre équipe a des développeurs front-end expérimentés"),
      bullet("Le contenu est structuré et répétitif (articles, produits, fiches)"),
      h3("Quand rester sur WordPress ou une solution traditionnelle"),
      bullet("L'équipe marketing doit être autonome sans développeur"),
      bullet("Le budget de développement est serré (< 15 000€)"),
      bullet("Le site est principalement un vitrine sans logique complexe"),
      h3("Notre expérience avec Sanity"),
      p("Sanity s'est imposé dans notre stack pour sa flexibilité de schémas et son studio personnalisable. Le GROQ (langage de requête) demande une semaine d'apprentissage, mais il est bien plus puissant que les requêtes REST classiques."),
      quote("Le headless n'est pas meilleur que le traditionnel — il est adapté à des besoins différents. Choisir headless pour un site vitrine simple, c'est utiliser un marteau-piqueur pour planter un clou."),
    ],
  },
  {
    title: "Contenu vidéo court pour les marques B2B : guide pratique 2026",
    slug: "contenu-video-court-b2b-guide-2026",
    excerpt: "Reels, Shorts, TikToks : les formats courts dominent les réseaux. Mais comment une entreprise B2B peut-elle produire ce contenu sans perdre sa crédibilité ni son budget ?",
    category: CATEGORIES.marketing,
    authors: [AUTHORS.arnaud, AUTHORS.nathan],
    publishedAt: "2026-05-07T08:00:00Z",
    body: [
      h2("Pourquoi le B2B doit s'y mettre"),
      p("LinkedIn booste massivement les vidéos natives courtes. YouTube Shorts touche une audience professionnelle croissante. Refuser le format court en B2B, c'est céder du terrain à vos concurrents qui, eux, s'y mettent."),
      h3("Les formats qui fonctionnent en B2B"),
      bullet("Le 'tip en 60 secondes' : un conseil actionnable, filmé en direct to camera"),
      bullet("Le 'behind the scenes' : montrez comment vous travaillez vraiment"),
      bullet("La 'question du secteur' : prenez position sur un sujet polarisant"),
      bullet("Le 'démystification' : détruisez une idée reçue de votre secteur"),
      h3("La production sans budget"),
      numbered("Smartphone récent + lumière naturelle de face = suffisant pour débuter"),
      numbered("Capcut ou DaVinci Resolve pour le montage (gratuits)"),
      numbered("1 journée par mois de tournage = 8 à 12 vidéos courtes"),
      h3("La distribution intelligente"),
      p("Publiez chaque vidéo sur LinkedIn, YouTube Shorts et Instagram Reels. Réutilisez le script en article de blog et le contenu clé en carrousel. Un tournage = 5 formats."),
      quote("La vraie barrière à la vidéo B2B n'est pas technique, elle est psychologique. La perfection est l'ennemie de la publication."),
    ],
  },
  {
    title: "Design System en 2026 : faut-il vraiment en construire un ?",
    slug: "design-system-guide-decision-2026",
    excerpt: "Un design system bien construit accélère le développement et renforce la cohérence de marque. Mais il représente un investissement conséquent. Pour qui, et à partir de quand ?",
    category: CATEGORIES.dev,
    authors: [AUTHORS.nathan, AUTHORS.arnaud],
    publishedAt: "2026-05-09T09:00:00Z",
    body: [
      h2("Le mythe du design system pour tout le monde"),
      p("Les grandes entreprises tech affichent leurs design systems (Atlassian Design, Material, Carbon). Cela fait rêver. Mais un design system est un produit à part entière — il demande des ressources pour être créé et maintenu."),
      h3("Quand ça vaut le coup"),
      bullet("Vous avez au moins 3 développeurs front-end qui travaillent en parallèle"),
      bullet("Vous maintenez plusieurs produits ou applications distinctes"),
      bullet("La cohérence visuelle est critique pour votre marque (banque, assurance, retail)"),
      h3("Quand c'est prématuré"),
      bullet("Startup early-stage : le produit change trop vite"),
      bullet("Équipe de 1 à 2 développeurs : le surcoût dépasse le bénéfice"),
      bullet("Site vitrine simple : une charte CSS suffit largement"),
      h3("L'alternative pragmatique : le design token"),
      p("Plutôt qu'un design system complet, définissez vos tokens (couleurs, typographie, espacement, radius) dans un fichier de configuration partagé. Vous gagnez 60 % de la valeur pour 10 % de l'effort."),
      quote("Le meilleur design system est celui que votre équipe utilise vraiment. Un composant parfait qui n'est pas adopté ne vaut rien."),
      h3("Notre recommandation"),
      p("Pour la majorité des PME : commencez par Tailwind CSS avec une configuration de tokens personnalisée. Si vous atteignez 5+ développeurs ou 3+ produits, reconsidérez un design system formel."),
    ],
  },
]

// ── Import ───────────────────────────────────────────────────────────────────
console.log(`Import de ${posts.length} articles…`)

let success = 0
let errors = 0

for (const post of posts) {
  const doc = {
    _type: 'post',
    title: post.title,
    slug: { _type: 'slug', current: post.slug },
    excerpt: post.excerpt,
    publishedAt: post.publishedAt,
    authors: post.authors.map((id, i) => ({
      _type: 'reference',
      _ref: id,
      _key: `author${i}`,
    })),
    categories: [{
      _type: 'reference',
      _ref: post.category,
      _key: 'cat0',
    }],
    body: post.body,
  }

  try {
    const result = await client.create(doc)
    console.log(`✓ "${post.title}" (${result._id})`)
    success++
  } catch (e) {
    console.error(`✗ "${post.title}" : ${e.message}`)
    errors++
  }
}

console.log(`\nTerminé : ${success} créés, ${errors} erreurs.`)
